### ISSUE TITLE
i can't set content using MobilePreview.display.content

### ISSUE THREAD

**Issue by nikky-ibl** [plyom/mobile-preview#1]
I can't set content for preview. 
i get error - Uncaught TypeError: Cannot read property 'content' of undefined.
my code
<html>
  <head>
    <script type="text/javascript" src="node_modules/jquery/dist/jquery.min.js"></script>
  </head>
<body onload="MobilePreview.setPlatformTo('ios');">
      <div class="mobile-preview">
      </div>

    <button onclick="MobilePreview.setPlatformTo('android');">Android</button>
    <button onclick="MobilePreview.setPlatformTo('ios');">iOS</button>
    <script type="text/javascript" src="node_modules/mobile-preview/src/mobile-preview.js"></script>
  </body>
<script>
      MobilePreview.container = $(".mobile-preview");
      console.log(MobilePreview);
      MobilePreview.display.content('<div class="hello">Hello World!</div>');
  </script>
</html>

**Comment by Pileggi** [comment]
Before you set the content you need to render the component. I created a folder with an example working.
